method: random
metric:
  goal: maximize
  name: f1_score
parameters:
  dropout:
    values: [0.1, 0.2, 0.3, 0.4, 0.5]
  learning_rate:
    values: [0.01, 0.001, 0.0001]
  hidden_size:
    values: [64, 128, 256, 512]
  layers:
    values: [1, 2, 3]
  weight_decay:
    values: [0.01, 0.001, 0.0001]
  dataset:
    value: datasets/subset_build_6kB_dataset.pth
  mode:
    value: active_learning
  active_points:
    value: 1
  active_iterations:
    value: 5 # 1000 typically
  num_forwards:
    value: 100
  batch_size:
    value: 32
  
  