method: random
metric:
  goal: maximize
  name: f1_score
parameters:
  dropout:
    min: 0.1
    max: 0.5
  learning_rate:
    min: 0.0001
    max: 0.01
  batch_size:
    values: [16, 32, 64]
  hidden_size:
    values: [64, 128, 256]
  layers:
    values: [1, 2, 3]
  dataset:
    value: datasets/subset_build_6kB_dataset.pth
  mode:
    value: active_learning
  active_points:
    value: 1
  active_iterations:
    value: 5 # 1000 typically
  num_forwards:
    value: 100
  